### ISSUE TITLE
Ability to call a model's class methods on the model's CollectionProxy

### ISSUE THREAD

**Issue by frewsxcv** [chanzuckerberg/sorbet-rails#104] opened 2019-07-31 14:01 UTC
**Describe the bug:**

Rails has the ability to call class methods on a model's CollectionProxy. See this SO for an example:

https://stackoverflow.com/questions/22304809/rails-ability-to-call-my-class-method-on-an-array

This behavior is not currently supported in sorbet-rails

**Steps to reproduce:**

N/A

**Expected behavior:**

It should typecheck

**Versions:**

- Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
- Rails: Rails 5.2.3
- Sorbet: Sorbet typechecker 0.4.4507 git d12b7144d2222398e0f28a772b7759fe26b2b9ba built on 2019-07-25 20:18:14 GMT with debug symbols
- Sorbet-Rails: 0.4.0

**Comment by jaredbeck** [comment] 2019-08-15 19:16
# Reproduced by sample app

Here is a sample app that reproduces this issue with the latest versions of all gems. (currently `sorbet-rails 0.5.0`)

https://github.com/jaredbeck/srb_ar_proxy

## Highlights

### Model

```ruby
# typed: true
class Task < ApplicationRecord
  def self.outstanding
    where 'due < ?', Time.current
  end
end
```

### Call Site

```ruby
# typed: true

# run me with bin/rails runner bin/outstanding.rb

puts Task.all.outstanding.count
```

### `tc` Output

```
bin/srb tc
bin/outstanding.rb:5: Method outstanding does not exist on Task::ActiveRecord_Relation https://srb.help/7003
     5 |puts Task.all.outstanding.count
             ^^^^^^^^^^^^^^^^^^^^
    sorbet/rails-rbi/models/task.rbi:128: Did you mean: Task::ModelRelationShared#extending?
     128 |  def extending(*args, &block); end
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

**Comment by manhhung741** [comment] 2019-08-15 19:20
Thanks for flagging. I think it’ll be a difficult problem to solve. Rails
dynamically routes missing methods from CollectionProxy to a Rails Model
(another class). All user-defined class methods in a rails model is
available in CollectionProxy. We can detect the method but it’ll likely be
difficult to generate the method _and_ the signature correctly. I don’t
know if sorbet provide any way to inflect signature for a method.

**Comment by jasnow** [comment] 2019-08-15 19:31
How does bin/outstnding.rb normally work (without sorbet)?

**Comment by manhhung741** [comment] 2019-08-15 19:33
Jared: For the example you gave, you can turn it into a scope easily.
Scopes are detected automatically by Sorbet-rails.

**Comment by manhhung741** [comment] 2019-08-18 03:32
I'll close this for now because I don't think it's possible.

**Closed by manhhung741** 2019-08-18 03:32 UTC
Labels: bug

**Comment by jaredbeck** [comment] 2019-08-19 02:39
> I'll close this for now because I don't think it's possible.

OK, thanks for looking into it.

https://github.com/chanzuckerberg/sorbet-rails/pull/133 documents this as a known issue.
