### ISSUE TITLE
Incompatibility after sorbet-0.5.5351

### ISSUE THREAD

**Issue by ptrippett** [chanzuckerberg/sorbet-rails#275] opened 2020-02-24 10:42 UTC
**Describe the bug:**

Including sorbet-rails with sorbet greater than 0.5.5351 causes an error during sorbet initialization

**Steps to reproduce:**

Gemfile
```
gem 'sorbet-rails', github: 'chanzuckerberg/sorbet-rails', ref: '8c99bb3'
gem 'sorbet-runtime', '0.5.5351'

group :development do
  gem 'sorbet', '0.5.5351'
end
```

```
Printing /tmp/d20200224-1598-1k3gwh5/reflection.rbi's symbol table into /tmp/d20200224-1598-1k3gwh5/reflection.json Traceback (most recent call last):         
6: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5357/bin/srb-rbi:237:in `<main>'         
5: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5357/bin/srb-rbi:196:in `main'         
4: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5357/bin/srb-rbi:121:in `init'         
3: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5357/bin/srb-rbi:232:in `block in make_step'         
2: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5357/lib/hidden-definition-finder.rb:38:in `main'         
1: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5357/lib/hidden-definition-finder.rb:47:in `main' /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5357/lib/hidden-definition-finder.rb:149:in `write_constants': /tmp/d20200224-1598-1k3gwh5/reflection.rbi had unexpected errors. Check this file for a clue: /tmp/d20200224-1598-1k3gwh5/reflection.json.err (RuntimeError)
```

Removing sorbet-rails from Gemfile causes no error to be raised,

**Expected behavior:**

No error is displayed during `srb init`

**Versions:**
- Ruby: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
- Rails: Rails 6.0.2.1
- Sorbet: Sorbet typechecker 0.5.5351 git 1cf785f649296b6084d4972bbfc904958231c953-dirty built on 2020-02-07 06:29:06 GMT debug_symbols=true
- Sorbet-Rails: 8c99bb3

**Comment by manhhung741** [comment] 2020-02-24 16:02
Thanks for reporting! Is there any information in the log file about what
error it encountered?

> Check this file for a clue: /tmp/d20200224-1598-1k3gwh5/reflection.json.err (RuntimeError)

**Comment by ptrippett** [comment] 2020-02-24 16:44
```
/tmp/d20200224-1598-1k3gwh5/reflection.rbi:190327: Invalid param, must be a :symbol https://srb.help/4011
      190327 |  Elem = type_member(out)
                       ^^^^^^^^^^^^^^^^
```

Then in newer sorbet versions again you get the sameish error just in the stacktrace :

```
Traceback (most recent call last):
        13: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/bin/srb-rbi:237:in `<main>'
        12: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/bin/srb-rbi:196:in `main'
        11: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/bin/srb-rbi:121:in `init'
        10: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/bin/srb-rbi:232:in `block in make_step'
         9: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:38:in `main'
         8: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:49:in `main'
         7: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:166:in `write_diff'
         6: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:197:in `serialize_constants'
         5: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:197:in `each'
         4: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:204:in `block in serialize_constants'
         3: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:261:in `serialize_class'
         2: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:286:in `without_errors'
         1: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:286:in `reject'
/home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:286:in `block in without_errors': undefined method `start_with?' for :out:Symbol (NoMethodError)```

**Comment by manhhung741** [comment] 2020-02-24 16:51
Great info! Thank you! I’ll look into this issue asap

**Comment by connorshea** [comment] 2020-02-25 01:55
Have you tried upgrading Sorbet? I'm fairly certain this is an issue with Sorbet that was fixed two weeks ago

https://github.com/sorbet/sorbet/issues/2626

**Comment by connorshea** [comment] 2020-02-25 02:04
I just tried sorbet-rails master with Sorbet `0.5.5390` on my Rails app and `bundle exec srb init` works fine for me 🤔 

I'm on Rails 6, if that matters. And it might be worth noting that I had Sorbet already working on it, which probably helps.

**Comment by manhhung741** [comment] 2020-02-27 00:51
@ptrippett I've also tested today with Sorbet `0.5.5400` and a sample Rails 5.0 app but I didn't run into any error. Can you try again after upgrading Sorbet?

**Comment by manhhung741** [comment] 2020-02-27 00:57
So I tried to pin the sorbet version to `0.5.5351` but I didn't run into any issue either. Maybe there is something else at play here. There is no reference to `Elem = type_member(out)` in Sorbet-Rails source code either. Can you doublecheck? I can think of only a few places that can show up:
- Old version of sorbet-rails (maybe just bad luck that I had a bad merge) -- using latest master should fix it?
- Some bug on sorbet-typed or sorbet itself? Grepping for `Elem = type_member(out)` should reveal where it comes from.

**Comment by manhhung741** [comment] 2020-03-02 22:02
Closing because this issue is not reproducible. It seems to happen with an outdated version of sorbet. Please feel free to re-open if it still doesn't work for you

**Comment by bradleybuda** [comment] 2020-03-12 22:33
I'm seeing the same issue and I can reproduce it reliably. It looks like that code (`Elem = type_member(:out)` is here: https://github.com/chanzuckerberg/sorbet-rails/blob/b4a91941171bf1314905a65a28debfff1b59a1bc/lib/bundled_rbi/type_assert.rbi#L7

I'm on a medium-sized rails codebase, rails 5.2.1. Got the error in `srb init` while upgrading to new versions of sorbet and sorbet-rails:

```
% git diff Gemfile.lock
diff --git a/Gemfile.lock b/Gemfile.lock
index 32ec88b2..0a13fdc2 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -116,7 +116,7 @@ GEM
       coffee-script-source
       execjs
     coffee-script-source (1.12.2)
-    commander (4.4.7)
+    commander (4.5.2)
       highline (~> 2.0.0)
     commonjs (0.2.7)
     concurrent-ruby (1.1.5)
@@ -286,10 +286,11 @@ GEM
     packable (1.3.10)
       backports
     parallel (1.17.0)
-    parlour (1.0.0)
-      commander (~> 4.4.0)
-      rainbow (~> 3.0.0)
-      sorbet-runtime
+    parlour (2.0.0)
+      commander (~> 4.5)
+      parser
+      rainbow (~> 3.0)
+      sorbet-runtime (>= 0.5)
     parser (2.6.3.0)
       ast (~> 2.4.0)
     pg (0.21.0)
@@ -459,17 +460,19 @@ GEM
       railties (>= 3.1)
       slim (>= 3.0, < 5.0)
     socksify (1.7.1)
-    sorbet (0.5.5351)
-      sorbet-static (= 0.5.5351)
+    sorbet (0.5.5434)
+      sorbet-static (= 0.5.5434)
     sorbet-coerce (0.2.3)
       polyfill (~> 1.8)
       safe_type (~> 1.1, >= 1.1.1)
       sorbet (>= 0.4.4704)
       sorbet-runtime (>= 0.4.4704)
-    sorbet-rails (0.5.9.1)
-      parlour (~> 1.0)
-    sorbet-runtime (0.5.5351)
-    sorbet-static (0.5.5351-universal-darwin-14)
+    sorbet-rails (0.6.0)
+      parlour (~> 2.0)
+      sorbet (>= 0.5)
+      sorbet-coerce (>= 0.2.3)
+    sorbet-runtime (0.5.5434)
+    sorbet-static (0.5.5434-universal-darwin-14)
     spring (2.0.2)
       activesupport (>= 4.2)
     spring-watcher-listen (2.0.1)
```

**Comment by manhhung741** [comment] 2020-03-12 22:41
Hmm we're already using Symbol
```
Elem = type_member(:out)
```
@bradleybuda can you grep for `Elem = type_member(out)` and see where it is defined in your repo? (file name, it's probably a autogerenated sorbet file

**Comment by manhhung741** [comment] 2020-03-12 22:56
Looks like the new error is that Symbol doesn't have `start_with?`, and smh Sorbet call `start_with?` on `:out`

**Comment by manhhung741** [comment] 2020-03-12 23:03
Can you try generating with the same version of Sorbet-rails, but a new version of Sorbet? I have a feeling this is an issue with Sorbet.

**Comment by manhhung741** [comment] 2020-03-12 23:06
I've tried running `srb init` with the `support/v5.2` app we have and it works, so I'm still in the dark with what's the root cause. 

Here is the line that raised the error: It seems it should be called with a line of code, not a single symbol. But other than that, IDK why it's given `:out` as input
https://github.com/sorbet/sorbet/blob/master/gems/sorbet/lib/hidden-definition-finder.rb#L286

The v5.2 sample Rails App:
https://github.com/chanzuckerberg/sorbet-rails/tree/1d51d35d52c73bef52789f82a8d18b0a210dbad0/spec/support/v5.2

**Comment by bradleybuda** [comment] 2020-03-12 23:12
Same error if I just update the sorbet version but not the sorbet-rails version:

Version update:
``` % git diff Gemfile.lock
diff --git a/Gemfile.lock b/Gemfile.lock
index 32ec88b2..23c49495 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -459,8 +459,8 @@ GEM
       railties (>= 3.1)
       slim (>= 3.0, < 5.0)
     socksify (1.7.1)
-    sorbet (0.5.5351)
-      sorbet-static (= 0.5.5351)
+    sorbet (0.5.5434)
+      sorbet-static (= 0.5.5434)
     sorbet-coerce (0.2.3)
       polyfill (~> 1.8)
       safe_type (~> 1.1, >= 1.1.1)
@@ -468,8 +468,8 @@ GEM
       sorbet-runtime (>= 0.4.4704)
     sorbet-rails (0.5.9.1)
       parlour (~> 1.0)
-    sorbet-runtime (0.5.5351)
-    sorbet-static (0.5.5351-universal-darwin-14)
+    sorbet-runtime (0.5.5434)
+    sorbet-static (0.5.5434-universal-darwin-14)
     spring (2.0.2)
       activesupport (>= 4.2)
     spring-watcher-listen (2.0.1)
```

The error:
```
Traceback (most recent call last):
	13: from /Users/brad/.rvm/gems/ruby-2.6.5@giza/gems/sorbet-0.5.5434/bin/srb-rbi:237:in `<main>'
	12: from /Users/brad/.rvm/gems/ruby-2.6.5@giza/gems/sorbet-0.5.5434/bin/srb-rbi:196:in `main'
	11: from /Users/brad/.rvm/gems/ruby-2.6.5@giza/gems/sorbet-0.5.5434/bin/srb-rbi:121:in `init'
	10: from /Users/brad/.rvm/gems/ruby-2.6.5@giza/gems/sorbet-0.5.5434/bin/srb-rbi:232:in `block in make_step'
	 9: from /Users/brad/.rvm/gems/ruby-2.6.5@giza/gems/sorbet-0.5.5434/lib/hidden-definition-finder.rb:38:in `main'
	 8: from /Users/brad/.rvm/gems/ruby-2.6.5@giza/gems/sorbet-0.5.5434/lib/hidden-definition-finder.rb:49:in `main'
	 7: from /Users/brad/.rvm/gems/ruby-2.6.5@giza/gems/sorbet-0.5.5434/lib/hidden-definition-finder.rb:166:in `write_diff'
	 6: from /Users/brad/.rvm/gems/ruby-2.6.5@giza/gems/sorbet-0.5.5434/lib/hidden-definition-finder.rb:197:in `serialize_constants'
	 5: from /Users/brad/.rvm/gems/ruby-2.6.5@giza/gems/sorbet-0.5.5434/lib/hidden-definition-finder.rb:197:in `each'
	 4: from /Users/brad/.rvm/gems/ruby-2.6.5@giza/gems/sorbet-0.5.5434/lib/hidden-definition-finder.rb:204:in `block in serialize_constants'
	 3: from /Users/brad/.rvm/gems/ruby-2.6.5@giza/gems/sorbet-0.5.5434/lib/hidden-definition-finder.rb:262:in `serialize_class'
	 2: from /Users/brad/.rvm/gems/ruby-2.6.5@giza/gems/sorbet-0.5.5434/lib/hidden-definition-finder.rb:287:in `without_errors'
	 1: from /Users/brad/.rvm/gems/ruby-2.6.5@giza/gems/sorbet-0.5.5434/lib/hidden-definition-finder.rb:287:in `reject'
/Users/brad/.rvm/gems/ruby-2.6.5@giza/gems/sorbet-0.5.5434/lib/hidden-definition-finder.rb:287:in `block in without_errors': undefined method `start_with?' for :out:Symbol (NoMethodError)
```

**Comment by bradleybuda** [comment] 2020-03-12 23:32
Weird new datapoint: If I use a local copy of sorbet-rails, checked out to `403c283`, like this in my Gemfile: `gem 'sorbet-rails', path: '~/src/sorbet-rails'`, the error goes away....

**Comment by bradleybuda** [comment] 2020-03-12 23:48
Bizarre - I built `sorbet-rails-0.6.0.gem` locally from `403c283` and installed it and I see the same error as when using the rubygems.org version (which makes sense I guess) But using the `path:` option to point at the same version on my local disk does not hit the error (as mentioned above).

Some problem with the way that sorbet scans gems for RBIs and/or sorbet-typed? I'm wildly speculating here...

**Comment by manhhung741** [comment] 2020-03-15 02:42
That must be related to sorbet’s gem detection :-/ let me see if I can
repro with a simple Rails repo & connect to sorbet-rails gem from Rubygems

**Comment by bradleybuda** [comment] 2020-03-16 04:52
Opened a PR on sorbet to fix the issue - it appears that there is no bug in sorbet-rails. Thanks for the help with debugging.

**Comment by manhhung741** [comment] 2020-03-17 01:57
Thanks for the fix! For anyone interested, this is the PR on sorbet repo: https://github.com/sorbet/sorbet/pull/2774

**Closed by manhhung741** 2020-03-17 01:57 UTC
Labels: bug

**Comment by jimmycuadra** [comment] 2020-09-02 09:20
This is still happening for me.

```
Traceback (most recent call last):
	6: from /Users/jimmy/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5888/bin/srb-rbi:237:in `<main>'
	5: from /Users/jimmy/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5888/bin/srb-rbi:196:in `main'
	4: from /Users/jimmy/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5888/bin/srb-rbi:121:in `init'
	3: from /Users/jimmy/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5888/bin/srb-rbi:232:in `block in make_step'
	2: from /Users/jimmy/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5888/lib/hidden-definition-finder.rb:38:in `main'
	1: from /Users/jimmy/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5888/lib/hidden-definition-finder.rb:47:in `main'
/Users/jimmy/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5888/lib/hidden-definition-finder.rb:151:in `write_constants': /var/folders/72/v_6r7k0d2x120hr5s01c5tz40000gn/T/d20200902-66114-accfod/reflection.rbi had unexpected errors. Check this file for a clue: /var/folders/72/v_6r7k0d2x120hr5s01c5tz40000gn/T/d20200902-66114-accfod/reflection.json.err (RuntimeError)
```

Versions:

* rails (6.0.3.2)
* sorbet (0.5.5888)
* sorbet-runtime (0.5.5888)
* sorbet-static (0.5.5888)

Seems like there's been a regression in Sorbet, or a similar error was introduced.
